### ISSUE TITLE
Cannot read property 'disableAutoDeploy' of undefined

### ISSUE THREAD

**Issue by talaikis** [haftahave/serverless-ses-template#20]
```bash
TypeError: Cannot read property 'disableAutoDeploy' of undefined
      at ServerlessSesTemplate.syncTemplatesOnDeploy (/codebuild/output/src768690066/src/node_modules/@haftahave/serverless-ses-template/src/index.js:132:53)
      at /codebuild/output/src768690066/src/node_modules/serverless/lib/classes/PluginManager.js:521:55
      at tryCatcher (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/codebuild/output/src768690066/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

Env:

```
Operating System:          linux
     Node Version:              12.18.0
     Framework Version:         2.2.0 (local)
     Plugin Version:            4.3.0
     SDK Version:               2.3.2
     Components Version:        3.4.3
``

**Comment by Enase** [comment]
@talaikis Thanks for report, going to fix it soon.

**Comment by Enase** [comment]
@talaikis Thanks again and feel free to use version [3.0.2](https://github.com/haftahave/serverless-ses-template/releases/tag/3.0.2)

**Comment by talaikis** [comment]
> @talaikis Thanks again and feel free to use version [3.0.2](https://github.com/haftahave/serverless-ses-template/releases/tag/3.0.2)

Wow, that's fast! :)

**Comment by Enase** [comment]
@talaikis np, you're welcome to share your ideas here https://github.com/haftahave/serverless-ses-template/issues/18
